[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
evm_version = "london"

# Flare Network Configuration
[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/bc/C/rpc"
flare = "https://flare-api.flare.network/ext/bc/C/rpc"
songbird = "https://songbird-api.flare.network/ext/bc/C/rpc"

[etherscan]
coston2 = { key = "${BLOCKSCOUT_API_KEY}", url = "https://coston2-explorer.flare.network/api" }
flare = { key = "${BLOCKSCOUT_API_KEY}", url = "https://flare-explorer.flare.network/api" }

# Test Configuration
[profile.test]
verbosity = 2
gas_reports = ["*"]

# CI Configuration
[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

# Deployment Configuration
[profile.deploy]
optimizer = true
optimizer_runs = 1000
via_ir = true

# Remappings for cleaner imports
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@flare-contracts/=lib/flare-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
